---
- name: pyats testing
  hosts: ios
  gather_facts: no
  connection: network_cli
  roles:
    - ansible-pyats
  tasks:
  - include_role:
      name: ansible-pyats
      tasks_from: snapshot
    vars:
      command: show vlan
      snapshot_file: "{{ inventory_hostname }}_ntp.json"
